name: Release SDK

on:
    workflow_dispatch:
        inputs:
            dryRun:
                description: 'Do a dry run to preview instead of a real release [true/false]'
                required: true
                default: 'true'

jobs:
    # SDK release is done from public/master branch.
    confirm-master-branch:
        name: Confirm release is run on public/master branch
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v1
            - name: Branch name
              run: |
                  BRANCHNAME=${GITHUB_REF##*/}
                  echo "pulling branch name, branch name is:"
                  echo $BRANCHNAME
                  if [ $BRANCHNAME != "master" ]
                  then
                    echo "You can only run a release from the master branch, you are trying to run it from ${BRANCHNAME}"
                    exit 1
                  fi

    # All new code is stored in internal/development. Release from public/master will merge changes from internal/development into
    # public/master, then run semantic-release on public/master to update changelog and release notes. Before semantic-release publishes
    # to npm, it builds the dist/ folder. Finally, commits from public/master are synced back to internal/master and internal/development.

    release-and-sync-repos:
        name: Release and Sync Repos
        runs-on: ubuntu-18.04
        needs: ['confirm-master-branch']
        env:
            GIT_AUTHOR_NAME: mparticle-bot
            GIT_AUTHOR_EMAIL: developers@mparticle.com
            GIT_COMMITTER_NAME: mparticle-bot
            GIT_COMMITTER_EMAIL: developers@mparticle.com

        steps:
            - name: Checkout internal/development
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  repository: mparticle/mparticle-web-sdk-internal
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: development

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm ci

            - name: Rebase internal/development to public/master for release
              run: |
                  git remote add public https://${{ secrets.GH_TOKEN_INTERNAL_TO_PUBLIC_TEST }}@github.com/mparticle/mparticle-web-sdk.git
                  git fetch public master
                  git checkout public/master
                  git rebase origin/development

            - name: Run tests
              run: npm run test

            - name: Release --dry-run
              if: ${{ github.event.inputs.dryRun == 'true'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_INTERNAL_TO_PUBLIC_TEST }}
              run: |
                  npx semantic-release --dry-run

            - name: Release
              if: ${{ github.event.inputs.dryRun == 'false'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_INTERNAL_TO_PUBLIC_TEST }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npx semantic-release

            - name: Merge release commits to internal master and internal development
              run: |
                  git push public HEAD:master
                  git push origin HEAD:master
                  git push origin HEAD:development
